apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app-demo
  template:
    metadata:
      labels:
        app: gitops-app-demo
    spec:
      containers:
      - name: gitops-app-demo
        image: docker.io/foreverlovewisdom/gitops-app-demo:release-8366c42
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          value: "throwaway-test-key-not-real-secret"
